name: Auto Build Update

on:
  push:
    paths:
      - "update-source/**"
      - "version.json"
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Create ZIP update
        run: |
          cd update-source
          zip -r ../update.zip .

      - name: Read version.json
        id: version
        run: echo "VERSION=$(jq -r .latest version.json)" >> $GITHUB_OUTPUT

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: Update v${{ steps.version.outputs.VERSION }}
          files: update.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
