name: Auto Build Update

on:
  push:
    paths:
      - "update-source/**"
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Zip update files
        run: |
          cd update-source
          zip -r ../update.zip .

      - name: Read version.json
        id: version
        run: echo "VERSION=$(jq -r .version version.json)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: Update v${{ steps.version.outputs.VERSION }}
          files: update.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
